# Generated by Django 3.2.9 on 2021-12-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20210209_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
